1) Display "unrecognized argument" error if there's some typo in arg name 2) Allow loading files from filename starts with "--"

diff --git a/bin/json2sqlite3 b/bin/json2sqlite3
--- a/bin/json2sqlite3
+++ b/bin/json2sqlite3
@@ -463,6 +463,7 @@ arg_created_column=
 arg_database_file=
 arg_deleted_column=
 arg_insert_if_empty=
+arg_json_files=()
 arg_preserve_created=
 arg_primary_key_column=
 arg_soft_delete=
@@ -516,6 +517,10 @@ while [[ $# -gt 0 ]]; do
       arg_created_column+=":INTEGER"
     fi
     arg_column_specs+=("${arg_created_column}")
+    ;;
+  "--debug" ) # usage: enable debug mode
+    DEBUG=1
+    set -x
     ;;
   "--deleted-column" | "--deleted-column="* ) # usage: specify a column name to contain deletion timestamp. you also can specify column type (e.g. deleted_at:INTEGER)
     if [[ "$1" == *"="* ]]; then
@@ -605,13 +610,30 @@ while [[ $# -gt 0 ]]; do
     VERBOSE=1
     VERBOSITY="$(( VERBOSITY + 1 ))"
     ;;
+  "--"* | "-"* )
+    { echo "${0##*/}: unrecognized argument: ${1:-}"
+      echo
+    } | error
+    usage
+    exit 1
+    ;;
   * )
     if [[ -z "${arg_database_file:-}" ]]; then
       arg_database_file="${1:-}"
     elif [[ -z "${arg_table_name:-}" ]]; then
-      arg_table_name="${1:-}"
+      if validate_ident "${1:-}"; then
+        arg_table_name="${1:-}"
+      else
+        error "${0##*/}: invalid table name: ${1:-}"
+        exit 1
+      fi
     else
-      break
+      if [[ -e "${1:-}" ]]; then
+        arg_json_files+=("${1:-}")
+      else
+        error "${0##*/}: no such file: ${1:-}"
+        exit 1
+      fi
     fi
     ;;
   esac
@@ -629,15 +651,23 @@ if ! command -v sqlite3 1>/dev/null 2>&1; then
 fi
 
 if [[ -z "${arg_database_file:-}" ]]; then
+  { echo "${0##*/}: database file was not given"
+    echo
+  } | error
   usage
   exit 1
 fi
 
 if [[ -z "${arg_table_name:-}" ]]; then
+  { echo "${0##*/}: table name was not given"
+    echo
+  } | error
   usage
   exit 1
-else
-  validate_ident "${arg_table_name}"
+fi
+
+if [[ $# -gt 0 ]]; then
+  arg_json_files+=("$@")
 fi
 
 if [[ -z "${arg_primary_key_column:-}" ]]; then
@@ -649,7 +679,11 @@ fi
 
 # read json from remainder of command line arguments, or standard input
 json_file="$(mktemp "${TMPDIR}/json_file.XXXXXXXX")"
-cat "$@" > "${json_file}"
+if [[ ${#arg_json_files[*]} -eq 0 ]]; then
+  cat > "${json_file}"
+else
+  cat -- "${arg_json_files[@]}" > "${json_file}"
+fi
 
 # fail early if the input data is not well-formed
 json_file_length=0
